#!/usr/bin/env bash
# This Infinite loop creates file with pid, catches signal, and removes file/exits:
# Note Ctrl-C (SIGINT), kill (SIGTERM), and ctrl-| (SIGQUIT)

rmfil_n_exit()
{
    rm -f /var/run/myscript.pid
    exit
}
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfil_n_exit" SIGTERM
trap "echo 'I hate the kill command'; rmfil_n_exit" SIGQUIT


echo $$ >> /var/run/myscript.pid
while (true)
do
    echo 'To infinity and beyond'
    sleep 2
done
