#!/usr/bin/env bash
# This is a script that displays the time for 12 hours and 59 minutes
# Display hours from 0 to 12
# Display minutes from 1 to 59

hr=0

while (( hr <= 12 ))
do
	echo "Hour: $hr"
	(( hr++ ))

	min=1
	while (( min <= 59 ))
	do 
		echo "$min"
		(( min++ ))
	done
done
